
//********************************************************************************
//*  Progammer:   Greg Piamonte 
//*  Date Written:  24 Aug 1995. 
//******************************************************************************** 

/*--------------------------------------------------------*/
/* Declare all exported names.                            */
/*--------------------------------------------------------*/
int _Optlink convertFahrenToCelsius( int fahrenheit );
int _Optlink convertCelsiusToFahren( int celsius );

