cd car
del *.lib *.obj *.xh *.xih *.ir *.dll *.exe out
cd ..\GARAGE
del *.lib *.obj *.xh *.xih *.ir *.dll *.exe out
cd ..\TICKET
del *.lib *.obj *.xh *.xih *.ir *.dll *.exe out
cd ..\TKTBOOKS
del *.lib *.obj *.xh *.xih *.ir *.dll *.exe out
cd ..\VALET
del *.lib *.obj *.xh *.xih *.ir *.dll *.exe out
cd ..\DLL
del *.dll
copy ..\dde4mbs.dll
cd ..\CLIENT
del *.lib *.obj *.xh *.xih *.ir *.dll *.exe out
cd ..
